version: '3.7'

services:
  app:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /share/Container/crater-data/:/var/www
      - /share/Container/crater-data/docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - crater

  db:
    image: mariadb
    restart: always
    volumes:
      #- db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      - /share/Container/crater-data/docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 50066:80
    volumes:
      - /share/Container/crater-data/:/var/www
      - /share/Container/crater-data/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
